apiVersion: apps/v1
kind: Deployment
metadata:
 name: backend-deployment
 labels:
   app: backend
spec:
 replicas: 1
 selector:
   matchLabels:
     app: backend
 template:
   metadata:
     labels:
       app: backend
   spec:
     containers:
       - name: backend
         # initial image; the workflow will override it with kubectl set image
         image: REPLACE_WITH_DOCKERHUB/backend:latest
         ports:
           - containerPort: 8080
         readinessProbe:
           httpGet:
             path: /actuator/health
             port: 8080
           initialDelaySeconds: 10
           periodSeconds: 10
