name: Build and Push Docker Image
on:
 push:
   branches: [ "main" ]
permissions:
 contents: read
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: 21
         cache: 'maven'
     - name: Build with Maven (skip tests temporarily)
       run: mvn -B -DskipTests=true clean package
     - name: SonarCloud Scan
       uses: SonarSource/sonarcloud-github-action@v2
       with:
        organization: "vineela1188"
        projectKey: "Backend"
       env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
     - name: Verify JAR build
       run: ls -l target/*.jar
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         args: >
           -Dsonar.projectKey=vineela1188_Backend
           -Dsonar.organization=vineela1188
           -Dsonar.host.url=https://sonarcloud.io
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     - name: Build and Push Docker Image
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
         # Removed cache lines since docker driver doesn't support cache export
         load: false
     - name: Print image tags
       run: |
         echo "✅ Image pushed successfully!"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:latest"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}"
