name: Build and Push Docker Image
on:
 push:
   branches: [ "main" ]
permissions:
 contents: read
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   services:
     sonarqube:
       image: sonarqube:lts
       ports:
         - 9000:9000
       options: >-
         --health-cmd="curl -f http://localhost:9000 || exit 1"
         --health-interval=10s
         --health-timeout=5s
         --health-retries=20
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: 21
         cache: 'maven'
     - name: Build with Maven (skip tests temporarily)
       run: mvn -B -DskipTests=true clean package
     - name: Wait for SonarQube
       run: |
         for i in {1..30}; do
           if curl -sSf http://localhost:9000 > /dev/null; then break; fi
           echo "Waiting for SonarQube to start ($i)..."
           sleep 5
         done
     - name: SonarQube Scan
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       run: |
         mvn clean verify sonar:sonar \
           -Dsonar.projectKey=my-java-app \
           -Dsonar.host.url=http://localhost:9000 \
           -Dsonar.login=${SONAR_TOKEN}}
     - name: Verify JAR build
       run: ls -l target/*.jar
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
     - name: Log in to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and Push Docker Image
       uses: docker/build-push-action@v5
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
         # Removed cache lines since docker driver doesn't support cache export
         load: false
     - name: Print image tags
       run: |
         echo "✅ Image pushed successfully!"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:latest"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}"
