name: Build, Dockerize and Push
on:
 push:
   branches: [ "main" ]
permissions:
 contents: read
jobs:
 build-and-push:
   runs-on: ubuntu-latest
   env:
     MAVEN_OPTS: -Dmaven.wagon.http.retryHandler.count=3
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         distribution: temurin
         java-version: 21
         cache: 'maven'
     
     - name: Build with Maven (skip tests optional)
       run: mvn -B -DskipTests=false clean package
       # If you want to skip tests in CI change -DskipTests=true
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         registry: docker.io
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         file: ./Dockerfile           # change path if Dockerfile is in another folder
         push: true
         tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
           ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
         cache-from: type=local,src=/tmp/.buildx-cache
         cache-to: type=local,dest=/tmp/.buildx-cache
     - name: Print image tags
       run: |
         echo "Image pushed:"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}"
         echo "${{ secrets.DOCKERHUB_USERNAME }}/backend:latest"
