name: Build & Push Backend
on:
 push:
   branches:
     - main
   paths:
     - "Backend/**"   # trigger only if backend folder changes
 workflow_dispatch:   # allow manual run
jobs:
 build-backend:
  runs-on: ubuntu-latest
  steps:
     # 1. Checkout code
  - name: Checkout repository
    uses: actions/checkout@v3
     # 2. Setup JDK 21 (since your backend uses JDK 21)
  - name: Set up JDK 21
    uses: actions/setup-java@v3
    with:
         distribution: 'temurin'
         java-version: '21'
 # 3. Build backend with Maven
  - name: Build Backend with Maven
    working-directory: Backend
    run: mvn clean package -DskipTests

 # 5. Build and push Docker image
  - name: Build & Push Docker image
    run: |
      docker build -t $IMAGE_NAME ./Backend

 
      sed -i "s|actioncr.azurecr.io/demo-backend:.*|${IMAGE_NAME}|g" k8s/deployment.yaml
      kubectl apply -f k8s/ -n default
